// <auto-generated />
using System;
using CalorieTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalorieTracker.data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260119134703_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("CalorieTracker.Data.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CaloriesPer100g")
                        .HasColumnType("REAL");

                    b.Property<double>("CarbsPer100g")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<double>("FatPer100g")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("ProteinPer100g")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("CalorieTracker.Data.Models.MealEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AmountGrams")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MealType")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EntryDate");

                    b.HasIndex("FoodId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("MealEntries");
                });

            modelBuilder.Entity("CalorieTracker.Data.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HeightCm")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightChangeRateKgPerWeek")
                        .HasColumnType("REAL");

                    b.Property<int>("WeightGoal")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityLevel = 2,
                            BirthDate = new DateTime(1990, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDate = new DateTime(2026, 1, 19, 13, 47, 3, 224, DateTimeKind.Utc).AddTicks(2670),
                            Gender = 2,
                            HeightCm = 170.0,
                            Name = "Default User",
                            WeightChangeRateKgPerWeek = 0.5,
                            WeightGoal = 1
                        });
                });

            modelBuilder.Entity("CalorieTracker.Data.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CarbsPercentage")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DietType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableMealReminders")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FatPercentage")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("MealReminderTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("ProteinPercentage")
                        .HasColumnType("REAL");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TrackMacros")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TrackWater")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseMetricSystem")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("CalorieTracker.Data.Models.WeightLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserProfileId1")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("LogDate");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("UserProfileId1");

                    b.ToTable("WeightLogs");
                });

            modelBuilder.Entity("CalorieTracker.Data.Models.MealEntry", b =>
                {
                    b.HasOne("CalorieTracker.Data.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CalorieTracker.Data.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("CalorieTracker.Data.Models.UserSettings", b =>
                {
                    b.HasOne("CalorieTracker.Data.Models.UserProfile", "UserProfile")
                        .WithOne()
                        .HasForeignKey("CalorieTracker.Data.Models.UserSettings", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("CalorieTracker.Data.Models.WeightLog", b =>
                {
                    b.HasOne("CalorieTracker.Data.Models.UserProfile", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalorieTracker.Data.Models.UserProfile", null)
                        .WithMany("WeightLogs")
                        .HasForeignKey("UserProfileId1");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("CalorieTracker.Data.Models.UserProfile", b =>
                {
                    b.Navigation("WeightLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
