// <auto-generated />
using System;
using CalorieTracker.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalorieTracker.data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260126144753_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("CalorieTracker.data.Models.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CaloriesPer100g")
                        .HasColumnType("REAL");

                    b.Property<double>("CarbsPer100g")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<double>("FatPer100g")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("ProteinPer100g")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("CalorieTracker.data.Models.MealEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AmountGrams")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MealType")
                        .HasMaxLength(50)
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.ToTable("MealEntries");
                });

            modelBuilder.Entity("CalorieTracker.data.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActivityLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasCompletedWizard")
                        .HasColumnType("INTEGER");

                    b.Property<double>("HeightCm")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserSettingsId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WeightChangeRateKgPerWeek")
                        .HasColumnType("REAL");

                    b.Property<int>("WeightGoal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("WizardCompletedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserSettingsId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("CalorieTracker.data.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CarbsPercentage")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DietType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableMealReminders")
                        .HasColumnType("INTEGER");

                    b.Property<double>("FatPercentage")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("MealReminderTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("ProteinPercentage")
                        .HasColumnType("REAL");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("TrackMacros")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TrackWater")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseMetricSystem")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("CalorieTracker.data.Models.WeightLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("LogDate");

                    b.ToTable("WeightLogs");
                });

            modelBuilder.Entity("CalorieTracker.data.Models.MealEntry", b =>
                {
                    b.HasOne("CalorieTracker.data.Models.Food", "Food")
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Food");
                });

            modelBuilder.Entity("CalorieTracker.data.Models.UserProfile", b =>
                {
                    b.HasOne("CalorieTracker.data.Models.UserSettings", "UserSettings")
                        .WithMany()
                        .HasForeignKey("UserSettingsId");

                    b.Navigation("UserSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
